[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "monospace"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true
headless = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
